### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by aras72h** [aras72h/weight-tracker#42]
```paython
Traceback (most recent call last):
  File "X:\weight-tracker\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\helpers.py", line 48, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\app.py", line 63, in index
    return render_template('index.html', weights=weights, avg_last=avg_last, avg_current=avg_current)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "X:\weight-tracker\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "X:\weight-tracker\templates\index.html", line 2, in top-level template code
    {% extends 'layout.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\templates\layout.html", line 64, in top-level template code
    {% block main %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\weight-tracker\templates\index.html", line 15, in block 'main'
    <strong>This Month's Average:</strong> {{ "{:.1f}".format(avg_current) }} kg
    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
INFO: 127.0.0.1 - - [01/Apr/2024 19:00:47] "GET / HTTP/1.1" 500 -

```

**Comment by aras72h** [comment]
It was working fine yesterday! 😀

**Comment by aras72h** [comment]
You know what? It's April's first and month has changed. Having no record for the new month caused app to crash!
